### PR TITLE
Better Module IoC

### PR DESCRIPTION
**Pull request by mecha**
Attempts to incorporate a solution for #3

### CODE REVIEW

**Review by XedinUnknown — COMMENTED** [review]
I like everything, except for one thing:
The documentation of the new `ModuleInterface` methods ties them to a concept of "application". I don't think we should make this relationship, and instead explain the purposes of each method separately from the context of their consumption.

**Comment by mecha** [comment]
@XedinUnknown Fair enough. What else should we omit? Should we also not mention other modules?

**Comment by XedinUnknown** [comment]
I think for one, yes, leave other modules out. Just explain that the `setup()` method SHOULD be used to set up the module; mention that it MAY provide values to the consumer. The `run()` method SHOULD be used to take action; mention that it MAY consume values provided by the consumer.

How does that sound?

**Comment by XedinUnknown** [comment]
Maybe for the `run()`, that SHOULD is a MUST :)

**Comment by mecha** [comment]
@XedinUnknown I was about to reply to comment on that!

**Comment by XedinUnknown** [comment]
Also, maybe the dependencies should be part of this interop standard.

**Comment by mecha** [comment]
Add a `getDependencies() : string[]|Stringable[]`?

**Comment by XedinUnknown** [comment]
Does that make sense to you? Because strictly speaking, the dependencies don't really influence anything about the *module*. Then again, neither does the module key.

**Comment by mecha** [comment]
Not sure. For many scenarios, modules _will_ have dependencies and there MUST be a mechanism that respects them for load order. Whether it merits a method in this interface, I'm not sure. It would be great if we have an interoperable way of identifying a module's dependencies, without having to know anything about the module system.

Regarding the module key ... I thought about it before I started these changes and arrived to the conclusion that it should be in the spec, for the simple reason that module identification should be controlled by the module. If different consumer applications give modules different keys, there would be no way to reliably identify modules. And module identification is a core mechanic when it comes to dependency resolution.

**Comment by XedinUnknown** [comment]
> module identification should be controlled by the module

Can't same logic be applied to module dependencies?

**Comment by mecha** [comment]
Yes of course. I'm just not 100% sure about adding the method. I mean strictly speaking, the module config should hold this info. So should the module copy that info into itself? Should the module config no longer have this info?

**Comment by XedinUnknown** [comment]
The module config can hold arbitrary pairs, including name and dependencies. However, the module config is not part of the module standard.

About the dependencies, how about a new `DependencyKeysAwareInterface`?

**Comment by mecha** [comment]
That implies a `getDependencyKeys()`. I think I prefer `getDependencies()` and therefore `DependenciesAwareInterface`.

**Comment by XedinUnknown** [comment]
I prefer that too. However, you are not retrieving dependencies; only their keys.

**Comment by mecha** [comment]
Fair argument. I just feel like if we apply this kind of logic to everything, we end up with ridiculous method and class names everywhere. To me, it's honestly just a personal preference. I see dependencies, in the context of this standard, as just keys anyway, so `getDependencies()` is fine for me. But I'm not terribly bothered with `getDependencyKeys()`. Your call.

**Comment by XedinUnknown** [comment]
Interesting idea: the `setup()` method could be used by the system to determine module *capabilities*. Judging by the services a module provides, the system can potentially build an index of that. Other modules could then declare dependencies on services, instead of modules. That sounds even more semantically correct. But for later.

**Comment by XedinUnknown** [comment]
> I see dependencies, in the context of this standard, as just keys

But they are not keys. A module, in our case, depends on other modules; not on their keys.

Taking into account my idea of depending on services in the future, maybe best think of an alternative name. I imagine, the config could say something like `require-modules: ["core"]`. So, this could be structurally retrievable via e.g. `getRequiredModuleKeys()`. The other method could perhaps be `getRequiredServiceKeys()` then.

**Comment by XedinUnknown** [comment]
Also, I thought of this problem with depending on services:
When you run `setup()` to retrieve the service keys, you have already run that - too late for order. However, then I realized that you can just store all the containers, and re-order them based on their modules' declared service dependencies. Also, you can apply the same ordering to the `run()` method call order.

**Comment by mecha** [comment]
But `getRequiredModuleKeys()` implies "getting the required *module keys*". In other words, it sounds as if the "module keys" are what is required. But in reality, it is the module that is required. You know what I mean?

**Comment by XedinUnknown** [comment]
You can read it like that. You can also read it as "get keys of required modules". That's just English for you. I think we should just go with this.

**Comment by mecha** [comment]
Sure. Then `getDependencyKeys()` or `getRequiredModuleKeys()`?

BTW this brings us back to the module having more awareness of "an application". Is that ok?

Frankly, I don't see any way around this. Perhaps it's because my intuition and past experience makes me _expect_ a module to have this kind of getter. I just hope we're not making the wrong choice here.

**Comment by XedinUnknown** [comment]
If you put it into a separate interface, this relieves the implementation from this burden of awareness.

**Comment by XedinUnknown** [comment]
> this brings us back to the module having more awareness of "an application"

Yep. And due to this, the idea of depending on services is now even more attractive!

**Comment by mecha** [comment]
@XedinUnknown `getDependencyKeys()` or `getRequiredModuleKeys()`?

**Comment by XedinUnknown** [comment]
Well, how about not depending on modules at all, and only on services? Like I wrote, this could remove application awareness.

**Comment by mecha** [comment]
Depends. Do we have the time to make a service sorting algorithm?

**Comment by XedinUnknown** [comment]
Good question.

**Comment by XedinUnknown** [comment]
Right, so I looked at the iterator implementation. Looks complicated to change. So therefore, the verdict is:

Do not implement service dependency based sorting for now. Use only module dependency sorting. Create a separate interface `getDependencies()`, and depend on that (doesn't require a change in sorting implementation). Will need to update RC interface for that, however.

**Comment by XedinUnknown** [comment]
Since we've kinda agreed to use `getDependencies()` (not some specific ones, like module or service dependencies), we can take this a bit further in terms of future compat. I think we should not formally declare that the dependency keys correspond to modules; instead, they can correspond to anything, i.e. services. So anything can be a dependency of a module, and services are anything. The only exception is that modules (which technically can also be services) would need special handling, since for uniform sorting they would be required to be in the container that they provide. But the container is immutable, so we can't automatically make sure the module is there. Alternatively, we can document that a module SHOULD make itself available via it's container for the `[module-key]/module` key - if it wants other modules to be able to depend on it. Thoughts?

**Comment by XedinUnknown** [comment]
Another possibility is that, since our application already has a composite container implementation, we could double-wrap modules. The container that would be added to the top container would not be the module's provided container, but a new composite container that would contain something that contains the module, and something that contains the module services. How about that?

**Comment by mecha** [comment]
For a more performant approach, we can just create a single container that contains the modules as services. This container can be added as the first container to the top-level composite container, effectively making it the eldest sibling of the module-given containers.

Anton pointed out that we had already explored this possibility and we had thought that this approach would not solve the problem. But now it seems like it's a more optimal solution for what Anton described in the previous comment. It achieves the same thing, but without an extra level of composite containers and without the need to create a container for just 1 service. The load order is preserved because the module-given containers can still be added to the top-level CC in a sorted fashion. The eldest sibling container would simply act as the default value provider for modules that do not include themselves as services.

To visualize, @XedinUnknown was suggesting the following:

C.Container - Composite Container
M.Container - Module-given Container

```
C.Container
	* C.Container
		* Container
			* [modulekey] -> ModuleInterface
		* Module-Given Container
	* C.Container
		* ...
	* C.Container
		* ...
```

The approach I suggested and which we previously ruled out:

```
C.Container
	* Container
		* [modulekey] -> ModuleInterface
		* [modulekey] -> ModuleInterface
		* [modulekey] -> ModuleInterface
		* ...
	* Module-Given Container
	* Module-Given Container
	* ...
```

The module services can be provided by the modules themselves, in which case they will come later in the load order thus overriding the ones in the eldest sibling. Modules can also override other modules this way.

**Comment by XedinUnknown** [comment]
It's important to understand that this is a good solution because module order is still preserved: the modules in the first container - the one that is automatically built to hold module instances - are in the order defined by module dependencies - just like the module-given containers are.

**Review by XedinUnknown — APPROVED** [review]

**Pull request merged**
